import {IntervalType} from '../types/types';

export const schedule: IntervalType[] = [
  'pomodoroTimeInMS',
  'shortBreakTimeInMS',
  'pomodoroTimeInMS',
  'shortBreakTimeInMS',
  'pomodoroTimeInMS',
  'shortBreakTimeInMS',
  'pomodoroTimeInMS',
  'longBreakTimeInMS',
];

export const wheelPickerNumbers = [
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  '10',
  '11',
  '12',
  '13',
  '14',
  '15',
  '16',
  '17',
  '18',
  '19',
  '20',
  '21',
  '22',
  '23',
  '24',
  '25',
  '26',
  '27',
  '28',
  '29',
  '30',
  '31',
  '32',
  '33',
  '34',
  '35',
  '36',
  '37',
  '38',
  '39',
  '40',
  '41',
  '42',
  '43',
  '44',
  '45',
  '46',
  '47',
  '48',
  '49',
  '50',
  '51',
  '52',
  '53',
  '54',
  '55',
  '56',
  '57',
  '58',
  '59',
  '60',
];

export const inspirationalLines = [
  'Dream big 🌟',
  'Never give up 👊',
  'Keep going 🚶‍♀️',
  'Stay positive 😃',
  'Stay focused 🔍',
  'Believe in yourself 🙌',
  'Take action 🔥',
  'Stay motivated 💪',
  'Make it happen 🌟',
  'Push yourself 💥',
  'Stay strong 💪',
  'Be persistent 🐘',
  'Be fearless 🦁',
  'Stay hungry 🍴',
  'Be unstoppable 🚀',
  'Be passionate ❤️',
  'Stay curious 🤔',
  'Stay committed 💯',
  'Be kind 💕',
  'Never lose hope 🌈',
  'You are enough 👍',
  'Success takes time 🕰️',
  'Embrace change 🌀',
  'Fail forward 🚶‍♂️',
  'Stay humble 🙏',
  'Find your purpose 🎯',
  'Make every day count ☀️',
  'Create your own luck 🍀',
  'Celebrate small wins 🎉',
  'Learn from failures 📚',
  'Stay authentic 💯',
  'Challenge yourself 🏋️‍♀️',
  'Rise above the noise 🌤️',
  'Be the change 🌍',
  'Live in the moment 🌟',
  'Do what you love ❤️',
  'Never stop exploring 🗺️',
  'Trust the journey 🚶‍♂️',
  'Focus on the positive 🌞',
  'Take risks 🎲',
  'Stay resilient 🌳',
  'Spread kindness 🌸',
  'Believe in the impossible 🤯',
  'Be a leader 🚀',
  'Invest in yourself 💰',
  'Inspire others 🌟',
  'Never settle 🚫',
  'Follow your heart ❤️',
  'Think outside the box 📦',
  'Keep moving forward 🏃‍♂️',
  'You got this! 💪',
  'Dream, then do 🌟',
  'Believe, achieve 🙌',
  'Make it happen 🚀',
  'Never give up 👊',
  'Stay the course 🚶‍♀️',
  'Take the leap 🤾‍♂️',
  'Rise and shine ☀️',
  'Stay the course 🚶‍♂️',
  'Keep moving forward 🚶‍♀️',
  'Be bold, be brave 🦁',
  'Think, act, achieve 🤔',
  'Inspire and be inspired 💡',
  'Dream, believe, achieve 🌈',
  'Stay focused, stay strong 🧘‍♀️',
  'Go big or go home 🏠',
  'Be the best 🏆',
  'Live your dream 🌟',
  'Follow your heart ❤️',
  'Never stop exploring 🌍',
  'The journey is everything 🌟',
  'Believe in yourself 🌟',
  'Create your destiny 🌟',
  'Stay hungry, stay humble 🍴',
  'Stay positive, stay strong 🤗',
  'Embrace the journey 🎉',
  'Be a game changer 🎮',
  'Hustle and heart 💪❤️',
  'Chase your passion 🌞',
  'Work hard, play hard 🎉',
  'Live, love, laugh 😄',
  'Follow your bliss 🌟',
  'Seize the day! ☀️',
  'Be the change 🌟',
  'Live your purpose 🌟',
  'Stay true to you 💯',
  'Inspire greatness daily 🌟',
  'Keep moving forward 🏃‍♂️',
  'Dare to be different 🦄',
  'Dream big, act now 🌟',
  'Create your legacy 🌟',
  'Be the one 🌟',
  'Make your mark 🎯',
  'Believe, create, achieve 🌟',
  'Never stop learning 📚',
  'Find joy in life 🎉',
  'Live with passion 🌟',
  'Love what you do ❤️',
  'Find your tribe 👥',
  'Do more, be more 🌟',
];
